name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # RTOS 폴더 안에 있는 설정파일을 기준으로 캐시 확인
          cache-dependency-path: './RTOS/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./RTOS

      - name: Build
        run: npm run build
        working-directory: ./RTOS

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite는 보통 dist 폴더에 결과물을 만듭니다.
          path: "./RTOS/dist/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4